//
//  MainInteractor.swift
//  viperProject
//
//  Created by Hamza Jerbi on 11/01/2019.
//  Copyright © 2019 Hamza Jerbi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com


import UIKit

class MainInteractor: MainPresenterToInteractorProtocol {
    
    var presenter: MainInteractorToPresenterProtocol?

}
